### ISSUE TITLE
Feedbacks on section 3, and informational 104 response being optional

### ISSUE THREAD

**Issue by dragonmigo** [httpwg/http-extensions#2272] opened 2022-10-21 00:23 UTC
Awesome protocol draft! Thank you!

I have some questions after reading it:

section 3.2 2) When uploading as series of parts, the example was phrased to give people impression that client is not allowed to send request body along with the initial upload creation procedure request. Which is not true after I fully read 4.2 and 6.

section 4.1 Why is the informational 104 response not required as long as server supports resumable upload feature? Since client depends on that to decide whether to use resumable upload? I've seen appendix, but wouldn't that confuse client implementation?

section 6. “The client SHOULD NOT automatically retry if a client error status code between 400 and 499 (inclusive) is received.” This is slightly confusing for this case:
a) client follows upload appending procedure and sent initial 100 bytes successfully
b) server did receive everything and sent 201, acknowledging 100 bytes.
c) However due to signal loss or terminated connection that server 201 did not reach client.
d) client is allowed to immediately retry and send the same 100 bytes again. 
e) server will respond with 409 conflict, with upload-offset: 100.
f) upon seeing that client should be able to resume upload, but from following chunk.
Is step f) not considered as an automatic retry?

**Comment by guoye-zhang** [comment] 2022-10-21 01:50
Thanks for bringing up these issues.

Section 3.2: Yes, it is allowed to send request body in the initial creation. We will clarify this in the example.

Section 4.1: Feature detection is only required if you are talking to an arbitrary server on the internet. If you already know that your own server supports this protocol, your client doesn't need to wait for 104. This is by design and allows deployment in environments where 1xx responses aren't usable.

Section 6: d) The client isn't allowed to immediately retry and send the same 100 bytes again. The client is only allowed to resume from either the offset from offset retrieving procedure, or a successful incomplete chunk. In this instance, the client should use offset retrieving procedure to lookup the current offset before resuming. Let me know if that works for you, or if you think we should change this part.

**Comment by dragonmigo** [comment] 2022-10-24 23:26
Thank you for your responses. The first 2 questions can be considered as closed, assuming we can clarify further in provided examples.


> Section 6: d) The client isn't allowed to immediately retry and send the same 100 bytes again.

The [current spec says](https://httpwg.org/http-extensions/draft-ietf-httpbis-resumable-upload.html#name-offset-retrieving-procedure-2):
> If an upload is interrupted, the client MAY attempt to fetch the offset of the incomplete upload by sending a HEAD request to the server with the same Upload-Token header field

I'm not sure if it's clear that client isn't allowed to retry sending the same chunked upload, as long as client thinks the previous attempt failed (probably by observing an interrupted connection, with no HTTP response header received yet).

**Comment by guoye-zhang** [comment] 2022-10-26 01:51
> If the offset in the Upload-Offset header field does not match the offset provided by the immediate previous Offset Retrieving Procedure ({{offset-retrieving}}), or the end offset of the immediate previous incomplete transfer, the server MUST respond with 409 (Conflict) status code.

The current meaning of "immediate previous incomplete transfer" is intended to be "immediate previous successful incomplete transfer", otherwise you are required to perform an offset retrieval.

I agree this is a reasonable thing to allow if you are doing chunked upload. Let me think of a way to make this work without complicating the other cases.

**Comment by Acconut** [comment] 2022-10-29 22:06
@guoye-zhang Do we just need to improve the wording of the spec here or is there an actual flaw in the upload flow here?

**Comment by guoye-zhang** [comment] 2022-10-29 22:12
I think some spec change might be desired. Let suppose someone just wants to do chunked upload and one chunk failed, are they forced to use offset retrieval or could they simply retry the last chunk? Current wording forces the former.

**Comment by Acconut** [comment] 2022-10-29 23:10
> Current wording forces the former.

I agree with this. Clients should first execute the Offset Retrieval Procedure to know what the latest offset is.

Sending a Upload Transfer Procedure with the last know offset will likely fail in most cases. In the best case, the offsets match. In the bad case, you get a 409 with the correct offset and then didn't save any requests. In the worst case, you have a HTTP client that only provides the response after the entire request has been sent and you only get to learn about the 409 after the entire body has been transferred.

All in all, a Offset Retrieval Procedure is the correct way to go IMO.

**Closed** 2022-11-05 20:07 UTC
Labels: resumable-upload
