### ISSUE TITLE
Avoid sending the digest when not used

### ISSUE THREAD

**Issue by yoavweiss** [httpwg/http-extensions#410] opened 2017-09-30 05:57 UTC
While discussing this, I heard raised concerns that:
* Adding cache digest support as currently specced may result in sending the digest even in cases where it is not used. Since initially this is likely to be most cases, shipping support is likely to result in performance regressions.
* OTOH, a digest negotiation mechanism is likely to result in an RTT worth of delay before the digest reaches the server.

A mechanism to solve this may look something like:
* Client SETTING parameter that tells the server "I'm going to send a cache digest, wait for it". If this setting is not present, the server should not wait for a digest before pushing.
* Server SETTING parameter that tells the client "I really like to get a cache digest next time around"
* Client implementations SHOULD/MUST maintain server preference for future sessions, and MAY not send a cache digest if a past session with that server did not include a "I want a digest" SETTING parameter.
* On the very first connection to a server, the client's cache is empty, so not sending the digest in that case has no penalty.

**Comment by mnot** [comment] 2017-10-01 14:34
Is it really a perf regression if the first RT is otherwise idle?

**Comment by yoavweiss** [comment] 2017-10-05 04:51
Since a typical website connects to multiple hosts, and connections established to fetch subresources often contend on bandwidth with other subresource fetches, sending digests for nothing could result in uplink bandwidth contention, and could delay subresource requests from going up.

**Comment by MikeBishop** [comment] 2018-01-04 22:56
Related to the question of when to send the digest, there's also the question of which digests to send when a connection could be authoritative for many hostnames.  A certificate with multiple SANs, or worse yet, a wildcard subdomain?  A client likely won't want to send the digest for all origins if the set is large, but sending it just for the first origin isn't likely to be sufficient assuming that the page has resources on subdomains / related domains.

**Comment by mnot** [comment] 2018-02-01 07:39
@MikeBishop the frame already has a slot for origin, so I think the approach would be to send separate digests for those origins you're interested in sending them for. If you find text that contradicts that (or if it isn't clear enough), or want to advocate another approach, open a separate issue?

**Comment by MikeBishop** [comment] 2018-02-01 17:58
Yes, but it's not the mechanics of how to send digests for multiple domains that I'm questioning.  It's determining *which* domains to send.  I see the thrust of this issue as being that the spec currently provides mechanics, but a lack of guidance to clients on how to use it.

The domains are likely coalesced because there are subresources that span them.  So while the client might know it wants to make a request of www.example.com, the server knows it wants to push resources for img.example.com and dynamic.example.com as well, and needs to see those digests.

For HTTP/QUIC and variable-length settings, I would say the server sends a setting that's the list of domains it would like to see the digests for.  That's less feasible in HTTP/2's 32 bits.  (You could overload ORIGIN, but assuming that the desired set is less than all the origins the server supports....)

**Comment by mnot** [comment] 2018-02-02 03:49
Or an extension flag on ORIGIN that indicates what origins the server wants CACHE_DIGEST for. Although arguably, simply getting an ORIGIN covering a given origin indicates interest in CD for it. If a server adds an origin to a connection, that's a pretty strong signal it expects to have requests for it.

**Comment by kazuho** [comment] 2018-02-02 05:38
I think that the draft already defines a way for a server to notify the client if it wants to see a digest (see [ACCEPT_CACHE_DIGEST parameter](http://httpwg.org/http-extensions/draft-ietf-httpbis-cache-digest.html#the-acceptcachedigest-settings-parameter)). However, the information is currently tied to the connection instead of the origin.

That said, one way of addressing the issue would be to add a way to define per-origin settings to the ORIGIN frame. Considering the fact that the use of the SETTINGS parameters is the suggested way for negotiating features, it would be natural to provide the opportunity to use them at a per-origin basis.

**Comment by mnot** [comment] 2018-02-12 00:46
A client->server "I'm going to send a CD, you might not want to push until you see it" setting sounds reasonable to me. I would imagine that clients that support CD will always send it; servers that think they know better can ignore it, of course.

ACCEPT_CACHE_DIGEST seems like it's optimised for the case that the browser doesn't want to send CD until it knows the server wants it, and it's OK if it doesn't show up in the first RT or two of the connection -- i.e., the client sends it sometime after the first request, and everyone is willing to wear a bit of inefficiency in the first few pushes, because we assume that there will be further interactions on the connection that can benefit from CD.

I think I agree that doesn't work so well for 3rd party content. 

However, making settings persistent beyond  the scope of a connection is something we've shied away from in the past; it's effectively defining a new kind of cache. Also, from a developer experience perspective, emitting new SETTINGS is not easy from some servers (never mind load balancers, CDNs, etc).

If @mikewest's [Origin Policy](https://wicg.github.io/origin-policy/) had any life in it, that might be appropriate here. Alternatively, we could define a well-known resource for this sort of origin-wide HTTP configuration along the lines of [Site-Wide HTTP Headers](https://mnot.github.io/I-D/site-wide-headers/). 

That would make the interaction something like:

~~~
c                                    s
+   SETTING WAIT_FOR_MY_DIGEST       +
|   SETTING I_WANT_HTTPSTUFF         |
|         GET /whatever              |
| +--------------------------------> |
|                                    |
|    PUSH /.well-known/httpstuff     |
| <--------------------------------+ |
|                                    |
|        200 OK /whatever            |
| <--------------------------------+ |
|                                    |
|        CACHE_DIGEST                |
| +--------------------------------> |
|                                    |
|    PUSH some other stuff           |
| <--------------------------------+ |
|                                    |
|                                    |




~~~

WDYT? Of course, we could also define a response header to do this, or a couple of other things.

**Comment by mnot** [comment] 2021-07-29 02:30
Closing, as we're no longer working on cache digests.

**Closed by mnot** 2021-07-29 02:30 UTC
Labels: cache-digest
