### ISSUE TITLE
Use of `Date` for creation time - potential conflict with some caching deployments

### ISSUE THREAD

**Issue by ezekg** [httpwg/http-extensions#1607] opened 2021-08-18 18:46 UTC
Background: I've added and have been field-testing HTTP response signatures in my business's API, per the earlier [Cavage HTTP draft spec](https://tools.ietf.org/id/draft-cavage-http-signatures-12.html). I hope that this is OK to post my issue here — trying to save other teams time in resolving this issue, granted they encounter it. I attempted to deliver a similar message to the ietf-http-wg mailing list, but since I'm not a W3 member, I don't think that's allowed, or at least it doesn't seem like it is.

With that said —

As you all may know, response signatures often utilize the standard `Date` response header to help prevent replay attacks, verify message integrity, among other things. In fact, the Cavage spec even defines the `Date` header as the default test for the response `Signature` header.

I wanted to give a PSA that Cloudflare rewrites the `Date` response header at the edge. Meaning, if a particularly unlucky request leaves a server at `14:01:26.999` with a `Date` header `Thu, 12 Aug 2021 14:01:26 GMT` and takes ~1ms to process at the edge by Cloudflare, the `Date` header from Cloudflare to the client ends up being `Thu, 12 Aug 2021 14:01:27 GMT` (note the change to the time's second). As of this issue, there is no way to disable this behavior.

Obviously, this is problematic when it comes to a cryptographic signature of an HTTP response, since the signature is invalidated once the `Date` header is modified. This ends up causing sporadic, hard-to-debug response signature verification failures, because the server is sending the correct dataset, but the client is not receiving the correct dataset. It's my understanding that the `Date` header is "the date and time at which the message _originated._"

I understand that the original draft spec by Cavage had the default test utilize the `Date` header, so this renders Cloudflare unusable for even the default test if signature reliability is a requirement (and it should be). I'm not sure if [the newer version of the spec](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures) also defaults to using `Date`, but regardless — if a signature contains the `Date` header and is proxied by Cloudflare, signatures will occasionally be invalidated.

A workaround is to use `X-Date` or similar instead of `Date`, but I do not find that to be a satisfactory workaround. And that doesn't take into account a default test that utilizes the standard `Date` header, which could be implemented more widely granted the draft spec is standardized in the future.

The other solution is to, of course, disable any proxies that behave in this way.

**Comment by LPardue** [comment] 2021-08-18 23:28
CDNs are acting as Gateways (by definition of HTTP https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-18.html#section-3.7). In this role they are the origin server.

Cloudflare is not unique in generating a current `Date` header field when they generate the response message, other CDNs do it. Indeed, using a cached `Date` header can result in serving a date that is not current, leading to user-agents classing the content as instantly stale.

As far as I can tell, draft-ietf-httpbis-message-signatures includes no examples where the `Date` header field is used to sign responses. 

Replay protections are not mentioned explicitly in draft-ietf-httpbis-message-signatures  (maybe they should) but it would seem the parameters defined in https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html#section-2.3.1, namely `created` and `expired` can allow for that type of thing.

**Comment by mnot** [comment] 2021-08-19 00:55
> CDNs are acting as Gateways (by definition of HTTP https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-18.html#section-3.7). In this role they are the origin server.

Sort of :)  Gateways are by definition undefined -- they can do pretty much whatever they want when the glue two protocols together, including when they glue together HTTP and HTTP. It happens to be that a profile of how to do that has gradually emerged over the years that we call 'CDN', but the edges are fuzzy still. That said, they're definitely allowed to update the `Date` header. Whether it's a good idea is another question.

> Cloudflare is not unique in generating a current Date header field when they generate the response message, other CDNs do it too.

That is [true](https://cache-tests.fyi/?id=other-date-update#).

> using a cached Date header can result in serving a date that is not current, leading to user-agents classing the content as instantly stale.

There are two cases to consider here. 

If the CDN is honouring `Cache-Control` and other "normal" HTTP freshness mechanisms, it can leave `Date` alone and HTTP's caching semantics will do their work. However, this has a couple of downsides. First, the responses it serves will have on average a smaller freshness lifetime than if they were served from origin, leading to less cache efficiency. Edith Cohen refers to this as the [age penalty](https://www.researchgate.net/publication/2324330_The_Age_Penalty_and_its_Effect_on_Cache_Performance).

Furthermore, when the stored response becomes stale on the CDN, it also becomes stale on browsers, leading to a 'thundering herd' effect, and requiring an end-to-end revalidation of the response (unless something like `stale-while-revalidate` is used). 

The other case is when the CDN has a separate freshness model -- especially when CDN freshness lifetimes are longer than the normal HTTP freshness lifetime, which is often the case. Here, if it doesn't update the HTTP headers (e.g., `Date`), the CDN can _often_ serve an already-stale response, even if its `Cache-Control` says otherwise.

The catch is that by having two separate freshness models (one for the CDN, one for the downstream caches), you have to _add_ them together to understand the maximum amount of time that something can be stored in cache. For example, if I configure my CDN to cache for one day, and "normal" cache-control to allow 12 hours, then something can live in cache for a total of one day, 12 hours. If you have a server-side reverse proxy as well, you have to add it in too.

I suspect many / most web developers don't understand that, and it's a bit of a gotcha if you're relying on expiry for things like rolling out new features. We as an industry could communicate about it better -- perhaps this should be discussed in the targeted cache control draft.

Back to the issue at hand -- I think the root of the problem is that `Date` is being used for more than one thing, and those uses are conflicting (we seem to be re-learning this lesson often ;). The fix is to either use a separate header, or configure your CDN to stop rewriting `Date` (with the caveat of all of the downsides above).

**Comment by LPardue** [comment] 2021-08-19 01:07
Thanks for the added detail @mnot .

I think the editors can talk with more authority here, but it seems to me that 

```
Creation Time:

    A timestamp representing the point in time that the signature was generated, as asserted by the signer.
```

and `created` and intended to address the ambiguity/dual use of `Date`.

**Comment by ezekg** [comment] 2021-08-19 14:22
@mnot Thanks for the in-depth explanation here around the `Date` header's relationship to caching — I didn't think about caching, simply because I'm not using Cloudflare for caching/as a CDN. I'm using CF as a web application firewall. So I guess one of the issues is that, even with caching turned off, CF still modifies the `Date` header.

@LPardue you're right that `created` likely works as an alternative to `Date`. Nearly all examples [in the spec](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures#section-4.1) include the `Date` header in the signature input (search `"date"` with double quotes and you can find the occurrences). E.g.:

```
 Signature-Input: sig1=("@method" "@target-uri" "host" "date" \
     "cache-control" "x-empty-header" "x-example");created=1618884475\
     ;keyid="test-key-rsa-pss"
```

I foresee more and more people encountering this issue once adoption increases, since CDNs are used so widely.

If `created` is a satisfactory alternative, I think the spec should mention that and forego utilizing the `Date` header entirely, or at least note the potential issues that could occur when utilizing `Date` with a CDN like Cloudflare.

**Comment by LPardue** [comment] 2021-08-19 14:44
> Nearly all examples in the spec include the Date header in the signature input (search "date" with double quotes and you can find the occurrences)

That's not entirely accurate. There's 11 instance of `Signature-Input:` in the draft, only 3 include `"date"`. The first, in section 4.1, is an abstract example of the `Signature-Input` header field. The other two in the appendices cover only request signatures, not responses. Requests are handled differently.

I agree the spec could be improved by noting deployment considerations.

**Comment by jricher** [comment] 2021-09-10 19:05
The `created` parameter is meant to timestamp the signature itself, where the `Date` header is the HTTP message -- these are two different considerations and could vary for all the reasons listed here plus any number of situations where the signature is applied to portions of a message at a different point than the message itself is fully instantiated. For all these reasons, relying on the `Date` header for both purposes is problematic. It's true that the Cavage draft used `Date`, but we've tried to remove most instances of covering the `Date` header from the examples, and in the two examples that have actual signatures, there's also a `created` field included. They happen to be the same value in the example in question, but that's simple to change if people would even notice that detail. The important thing is that they convey different information.

As it stands, the `created` field is defined for its specific purpose, but we will add language expanding on that discussion. There are a few other fields where similar discussion is needed (the `Host` field comes to mind immediately), and the editors are working on the security and privacy considerations sections currently to include this discussion.

**Comment by ioggstream** [comment] 2021-09-21 22:29
@ezekg pls check this old thread https://github.com/w3c-ccg/http-signatures/issues/35 wrt `Date` vs `created` on a previous version of the signature spec. Cavage had a lot of quirks that have been fixed in this spec!

**Closed** 2021-12-20 18:44 UTC
Labels: signatures
