### ISSUE TITLE
Cache-Status granularity issues, reintroduce summary token?

### ISSUE THREAD

**Issue by triblondon** [httpwg/http-extensions#994] opened 2019-11-28 23:47 UTC
The last time I reviewed this spec it had essentially a single key, the header itself, and an enum of possible values, which would be repeated if the response passed through multiple cache layers:

```
cache-action   = %s"HIT_FRESH"
               / %s"HIT_STALE"
               / %s"HIT_REFRESH_MODIFIED"
               / %s"HIT_REFRESH_NOT_MODIFIED"
               / %s"HIT_REFRESH_STALE"
               / %s"MISS"
               / %s"MISS_CLIENT"
               / %s"BYPASS"
               / %s"ERROR"
```

There was certainly scope to make this more detailed, but it seemed elegant enough and was essentially a like for lie replacement of what most caches already do.  The current version goes too far in my opinion.  I see the following use cases:

1. Developer of site using the header interactively for debugging
2. Developers' CI tools asserting expected behaviours against the header for smoke testing
3. Developers monitoring their CDN partner's cache efficacy (via RUM, I guess, ideally)
4. Cache operators optimising their behaviour based on a better understanding of upstream cache status
5. Researchers wanting to understand the state of the web more generally

Many of these use cases arguably call for the most granular and detailed possible information to be included, but I would argue that 95% of the value of this type of header is use case 1.  And in the latest revision, we have lost a simple, clear status token.

I'd propose reintroducing an enum of statuses, and support the additional params as enrichment. So a complexish example:

```
Cache-Status: MISS; cache=fastly-bwi-1234; collapse-hit=?1,
              HIT_FRESH; cache=akamai; res-fresh=289
```

The current proposal already has a keyless param, for the cache name.  I'm essentially proposing that we add a key to that param, and introduce a new keyless param, for the summary cache status.

The result is that this is MUCH easier for developers to scan, a minimal implementation is more immediately useful (because as a cache you need only implement the keyless status param, not any of the others) and therefore implementation/adoption could be faster.  A minmal example could be (exactly as per the earlier spec draft):

```
Cache-Status: HIT_FRESH
```

Whereas the minimal implementation of the current draft would be something like `Cache-Status: ExampleCache` and (at least for use case 1) that's unlikely to tell anyone anything they don't already know.

**Comment by mnot** [comment] 2019-12-03 08:11
So, the background for this is #766. In a nutshell:

* The PREFIX_SUFFIX approach to defining cache tags was imprecise and difficult to extend / maintain
* We wanted a clean break from the `X-Cache` syntax to emphasise that this need to be re-implemented, not just ported over (i.e., incompatibility with exisiting syntax is a feature, not a bug)

Several people also liked the alignment with `Proxy-Status` in terms of using the node name as the "primary" key that parameters are put onto.

Looking at your example:

~~~
Cache-Status: MISS; cache=fastly-bwi-1234; collapse-hit=?1,
              HIT_FRESH; cache=akamai; res-fresh=289
~~~

it would look like this in the current draft;

~~~
Cache-Status: fastly-bwi-1234; fwd=uri-miss; collapse-hit=?1,
            Akamai; res-fresh=289
~~~

Would it be helpful if we spelled it slightly differently, e.g.:

~~~
Cache-Status: fastly-bwi-1234; type=URI_MISS; collapse-hit=?1,
            Akamai; type=FRESH, res-fresh=289
~~~

That uses a few more bytes, of course.

**Comment by triblondon** [comment] 2019-12-04 05:43
This suggestion seems to be basically what I want except that the new `type` subfield should be keyless, and the keyless subfield should be keyed as `cache`, resulting in:

```
Cache-Status: URI_MISS; cache=fastly-bwi-1234; collapse-hit=?1,
              FRESH; cache=akamai; res-fresh=289
```

**Comment by mnot** [comment] 2020-02-25 05:03
I don't think we're going to reintroduce the all-in-one tokens for reasons previously discussed, but I've tweaked things to be a bit friendlier (see most recent editors' draft); e.g., the examples above would be:

~~~
Cache-Status: fastly-bwi-1234; fwd=uri-miss; collapsed,
            Akamai; hit; ttl=289
~~~

**Comment by mnot** [comment] 2020-07-15 08:23
Talked to @triblondon, he thinks this has been addressed by recent changes.

**Closed by mnot** 2020-07-15 08:23 UTC
Labels: cache-header
